#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kirigami-gallery
Version  : 18.12.2
Release  : 2
URL      : https://download.kde.org/stable/applications/18.12.2/src/kirigami-gallery-18.12.2.tar.xz
Source0  : https://download.kde.org/stable/applications/18.12.2/src/kirigami-gallery-18.12.2.tar.xz
Source99 : https://download.kde.org/stable/applications/18.12.2/src/kirigami-gallery-18.12.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0
Requires: kirigami-gallery-bin = %{version}-%{release}
Requires: kirigami-gallery-data = %{version}-%{release}
Requires: kirigami-gallery-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : qtbase-dev mesa-dev

%description
# Kirigami Gallery
Example application which uses all features from kirigami, including links to the sourcecode, tips on how to use the components and links to the corresponding HIG pages and code examples on cgit

%package bin
Summary: bin components for the kirigami-gallery package.
Group: Binaries
Requires: kirigami-gallery-data = %{version}-%{release}
Requires: kirigami-gallery-license = %{version}-%{release}

%description bin
bin components for the kirigami-gallery package.


%package data
Summary: data components for the kirigami-gallery package.
Group: Data

%description data
data components for the kirigami-gallery package.


%package license
Summary: license components for the kirigami-gallery package.
Group: Default

%description license
license components for the kirigami-gallery package.


%prep
%setup -q -n kirigami-gallery-18.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549886233
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1549886233
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kirigami-gallery
cp LICENSE.LGPL-2 %{buildroot}/usr/share/package-licenses/kirigami-gallery/LICENSE.LGPL-2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kirigami2gallery

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kirigami2.gallery.desktop
/usr/share/locale/ca/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/cs/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/de/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/es/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/fr/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/gl/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/nl/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/nn/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/pl/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/pt/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/sk/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/sv/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/uk/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/kirigamigallery_qt.qm
/usr/share/metainfo/org.kde.kirigami2.gallery.appdata.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kirigami-gallery/LICENSE.LGPL-2
